# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7de0d1c94b2b050ee9978d982a2906dbc6db21a95db16664795e89fa069c2a1a1eff0718b82f3ee95ca2c3966c0ad792e31d51debe5f1bc3d1dd6c90433b0c7

test:
  secret_key_base: 891717c8f21b319f01b255bb604e0c44a979ccaff86c11e186246bdfb1402535bc229004f5ff997565f06b277bc42bf3d218e3807306dfbd87798dff4764ee33

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
